percent: 50
groundLevel: 64
alertEnabled: true
includeMiners: true
alerts:
  onMorningText: Wakey, wakey, rise and shine... Good Morning everyone!
  onSleepText: is now sleeping.
  onWakeText: has left their bed.